import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    'nav.getAccess': 'Get Access',
    
    // Footer
    'footer.desc': "Cultivating meaningful connections for Hong Kong's real estate professionals. Authentic strategies. Sustainable growth. Human-centric marketing.",
    'footer.explore': 'Explore',
    'footer.connect': 'Connect',
    'footer.rights': 'All rights reserved.',
    
    // Home
    'home.badge': 'Next-Gen Intelligent Marketing Infrastructure',
    'home.hero.title': 'Automated Growth',
    'home.hero.subtitle': 'for Elite Real Estate Agents',
    'home.hero.desc': 'We leverage generative video, autonomous agents, and predictive algorithms to find premium buyers before your competitors do.',
    'home.hero.cta.explore': 'Explore Infrastructure',
    'home.hero.cta.demo': 'Schedule a Consult',
    'home.float.roi': 'Campaign ROI',
    'home.float.industry': 'vs. industry avg.',
    'home.float.lead': 'New Lead Qualified',
    'home.float.budget': 'Budget',
    'home.pillars.title': 'The Intelligent Advantage',
    'home.pillars.desc': 'We combine three powerful technologies to create an unstoppable marketing engine for your real estate business.',
    'home.pillars.video.title': 'Generative Video',
    'home.pillars.video.desc': 'We turn static photos into cinematic video property content automatically, capturing 400% more engagement.',
    'home.pillars.video.detail': 'Our AI analyzes your property photos to create cinematic video property content complete with professional voiceovers, background music, and dynamic transitions. No filming crew required.',
    'home.pillars.agents.title': 'Autonomous Agents',
    'home.pillars.agents.desc': 'Our automated CRM system engages leads instantly, 24/7, qualifying budget and intent before you wake up.',
    'home.pillars.agents.detail': 'Never miss a lead again. Our AI agents engage potential buyers instantly on WhatsApp and Messenger, answering questions and booking appointments while you sleep.',
    'home.pillars.predictive.title': 'Predictive Targeting',
    'home.pillars.predictive.desc': 'Algorithms analyze thousands of data points to identify high-net-worth buyers ready to transact.',
    'home.pillars.predictive.detail': 'Stop wasting budget on cold leads. We analyze thousands of data points to target buyers who are actively looking for properties in your specific price range and area.',

    'home.how.title': 'How It Works',
    'home.how.desc': 'A streamlined three-step process to transform your lead generation.',
    'home.how.1.title': 'Connect',
    'home.how.1.desc': 'Integrate your listings and social profiles with our secure platform.',
    'home.how.1.detail': 'We integrate directly with your Facebook and Instagram accounts. Simply upload your property photos and key selling points to our secure dashboard.',
    'home.how.2.title': 'Automate',
    'home.how.2.desc': 'Our AI generates content and launches targeted campaigns instantly.',
    'home.how.2.detail': 'Our system automatically generates professional video ads, writes compelling copy, and sets up targeted ad campaigns optimized for your specific audience.',
    'home.how.3.title': 'Convert',
    'home.how.3.desc': 'Receive pre-qualified leads directly to your phone, ready to view.',
    'home.how.3.detail': 'Sit back as high-quality leads start flowing in. You get instant notifications for booked viewings and hot leads ready to buy.',
    'home.pain.title': 'Stop Relying on',
    'home.pain.subtitle': 'Outdated Methods',
    'home.pain.1': 'Portal saturation means your listings get buried.',
    'home.pain.2': 'Manual follow-ups are too slow for modern buyers.',
    'home.pain.3': 'Generic ads waste budget on unqualified clicks.',
    'home.solution.title': 'The BasisHK Solution',
    'home.solution.1.title': 'Dominance',
    'home.solution.1.desc': 'Own the feed with high-frequency video content.',
    'home.solution.2.title': 'Speed',
    'home.solution.2.desc': 'Respond in seconds, not hours, with automation.',
    'home.solution.3.title': 'Precision',
    'home.solution.3.desc': 'Target only the top 1% of qualified buyers.',
    'home.cta.title': 'Ready to',
    'home.cta.subtitle': 'Modernize?',
    'home.cta.desc': 'Join the top 1% of agents using intelligent infrastructure to dominate the market.',
    'home.cta.button': 'Start Now',
    'home.trusted.title': 'Trusted by Agents from Top Developers',
    'home.gallery.title': 'Cinematic Excellence',
    'home.gallery.subtitle': 'See what our AI can create for your listings.',
    'home.gallery.tag.luxury': 'Luxury',
    'home.gallery.tag.tour': 'Virtual Tour',
    'home.gallery.tag.promo': 'Social Promo',
    'home.gallery.tag.drone': 'Drone View',

    // Case Studies
    'home.cases.title': 'Proven Results',
    'home.cases.subtitle': 'Real success stories from Hong Kong agents.',
    'home.cases.midlevels.title': 'Mid-Levels Luxury',
    'home.cases.midlevels.desc': 'Cinematic video property content generated 15k+ organic views.',
    'home.cases.midlevels.stat1': '15k+',
    'home.cases.midlevels.label1': 'Video Views',
    'home.cases.midlevels.stat2': '14 Days',
    'home.cases.midlevels.label2': 'Time to Sell',
    'home.cases.kaitak.title': 'Kai Tak Investment',
    'home.cases.kaitak.desc': 'Vertical video ads drove 45 leads in 48 hours.',
    'home.cases.kaitak.stat1': '45 Leads',
    'home.cases.kaitak.label1': 'Volume',
    'home.cases.kaitak.stat2': '$12',
    'home.cases.kaitak.label2': 'Cost Per Lead',
    'home.cases.saikung.title': 'Sai Kung Villa',
    'home.cases.saikung.desc': 'Drone showcase captured 12 high-net-worth buyers.',
    'home.cases.saikung.stat1': '12 Buyers',
    'home.cases.saikung.label1': 'Qualified Leads',
    'home.cases.saikung.stat2': '14.2%',
    'home.cases.saikung.label2': 'Engagement Rate',

    // Services
    'services.title': 'Intelligent Infrastructure',
    'services.subtitle': 'Choose the growth engine that fits your scale.',
    'services.monthly': 'Monthly',
    'services.quarterly': 'Quarterly',
    'services.save': 'Save 5%',
    'services.plan.starter': 'Starter',
    'services.plan.growth': 'Growth',
    'services.plan.agency': 'Agency',
    'services.plan.starter.desc': 'Essential automation for individual agents.',
    'services.plan.growth.desc': 'Advanced tools for high-volume producers.',
    'services.plan.agency.desc': 'Full-scale infrastructure for teams.',
    'services.feature.video': 'AI Property Videos',
    'services.feature.bot': 'Lead Capture Bot',
    'services.feature.content': 'Social Media Content',
    'services.feature.consultancy': 'Property Ad Consultancy',
    'services.feature.report': 'Performance Report',
    'services.feature.support': 'Email Support',
    'services.feature.manager': 'Dedicated Account Manager',
    'services.feature.basic': 'Basic',
    'services.feature.advanced': 'Advanced',
    'services.feature.posts': 'Posts',
    'services.feature.monthly': 'Monthly',
    'services.feature.revisions': 'Unlimited Revisions',
    'services.feature.weekly': 'Weekly',
    'services.feature.aiOptimizer': 'AI Property Listing Optimizer',
    'services.feature.basicPortal': 'Basic Branded Property Portal',
    'services.feature.limitedListings': 'Limited Listings + Auto Sync',
    'services.feature.unlimitedListings': 'Unlimited Listings + Auto Sync',
    'services.feature.adsBoosting2k': 'Ads Boosting Service (Worth $2,000)',
    'services.feature.adsBoosting4k': 'Ads Boosting Service (Worth $4,000)',
    'services.feature.videos': 'Videos',
    'services.plan.videoOnly': 'Custom AI Property Videos',
    'services.plan.videoOnly.desc': 'Need videos only? Get high-quality AI-generated property videos without a subscription.',
    'services.videoSlider.label': 'Select number of videos',
    'services.videoSlider.perVideo': 'per video',
    'services.videoOnly.feature1': '4K Cinematic Quality',
    'services.videoOnly.feature2': 'Professional Voiceover',
    'services.videoOnly.feature3': '48-Hour Delivery',
    'services.videoOnly.feature4': 'Unlimited Revisions',
    'services.videoOnly.cta': 'Order Videos Now',
    'services.select': 'Select Plan',
    'services.popular': 'Most Popular',
    'services.faq.title': 'Frequently Asked Questions',
    'services.faq.subtitle': 'Everything you need to know about our services and billing.',
    'services.faq.q1': 'What does "Unlimited Revisions" mean?',
    'services.faq.a1': 'We want you to be 100% satisfied with your content. You can request as many changes as needed to the video edits, captions, or ad copy until it perfectly matches your vision.',
    'services.faq.q2': 'Is there a minimum contract period?',
    'services.faq.a2': 'No, all our plans are month-to-month. You can cancel or upgrade at any time. However, choosing quarterly billing saves you 5%.',
    'services.faq.q3': 'How quickly can I get my first video?',
    'services.faq.a3': 'Once you upload your property photos, our AI generates the initial draft within minutes. After your review, the final polished version is typically ready within 48 hours ready for revisions by our creative team.',
    'services.faq.q4': 'Do you handle the ad spend budget?',
    'services.faq.a4': 'The ad spend is paid directly to the platforms (Facebook/Instagram) by you. Our fee covers the management, optimization, and creative production.',
    'services.faq.q5': 'What is the Advanced Lead Capture Bot?',
    'services.faq.a5': 'Our Advanced Lead Capture Bot is an AI-powered assistant that engages visitors 24/7. It qualifies leads by asking key questions about their budget, preferences, and timeline, ensuring you only spend time on high-intent prospects.',
    'services.faq.q6': 'How does Predictive Targeting work?',
    'services.faq.a6': 'Predictive Targeting uses machine learning to analyze market trends and user behavior. It identifies potential buyers who are most likely to convert, allowing us to serve your ads to the most relevant audience before your competitors do.',
    'services.faq.q7': 'What does a Dedicated Account Manager do?',
    'services.faq.a7': 'Your Dedicated Account Manager is your strategic partner. They oversee your campaigns, provide monthly performance reports, and offer personalized advice to optimize your marketing strategy, ensuring your goals are met.',

    // About
    'about.title': 'Built by Agents, For Agents',
    'about.desc': 'We are not just tech developers. We are real estate veterans who understand the hustle.',
    'about.mission.1': 'BasisHK was born from frustration. As former agents in Hong Kong\'s cutthroat market, we saw how traditional marketing failed to keep up with the digital age.',
    'about.mission.2': 'We spent years building the tools we wished we had: systems that automate the grunt work, qualify leads while we sleep, and let us focus on what matters—closing deals.',
    'about.mission.3': 'Today, we empower individual agents with the same enterprise-grade technology used by global firms, leveling the playing field for everyone.',
    'about.stat.focus': 'Real Estate Focus',
    'about.stat.uptime': 'System Uptime',
    'about.stat.growth': 'Dedicated to Your Growth',
    'about.values.title': 'Our Core Values',
    'about.values.integrity': 'Agent-First',
    'about.values.integrity.desc': 'We build features that solve real problems, not just shiny toys.',
    'about.values.innovation': 'Transparency',
    'about.values.innovation.desc': 'No hidden fees or vanity metrics. We track what makes you money.',
    'about.values.results': 'Excellence',
    'about.values.results.desc': 'We believe every agent deserves world-class infrastructure.',
    'about.cta.title': 'Join the Revolution',
    'about.cta.button': 'Get in Touch',

    // Contact
    'contact.title': 'Contact Us',
    'contact.desc': 'Interested in our services? Please fill out the form to schedule a consultation with our marketing team. We look forward to discussing how we can assist in growing your real estate business.',
    'contact.hours.title': 'Office Hours',
    'contact.hours.desc': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contact.email.title': 'Email',
    'contact.form.firstName': 'First Name',
    'contact.form.lastName': 'Last Name',
    'contact.form.agency': 'Real Estate Agency',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.budget': 'Marketing Budget (Monthly)',
    'contact.form.budget.placeholder': 'Select range',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Please describe your current marketing challenges...',
    'contact.form.submit': 'Submit Inquiry',
    'contact.form.submitting': 'Submitting...',
    'contact.toast.title': 'Inquiry Received',
    'contact.toast.desc': 'Thank you for contacting BasisHK. A representative will respond to your inquiry within 24 hours.',
    
    // Contact Form - New Keys
    'contact.step1.title': 'Tell us about yourself',
    'contact.step1.desc': 'Let us know who you are so we can personalize your experience.',
    'contact.step2.title': 'Contact Details',
    'contact.step2.desc': 'How can we reach you to discuss your needs?',
    'contact.step3.title': 'What interests you?',
    'contact.step3.desc': 'Select the services you\'re interested in and tell us more.',
    'contact.info.title': 'Get in Touch',
    'contact.phone.title': 'Phone',
    'contact.response.time': 'We typically respond within 24 hours during business days.',
    'contact.trust.title': 'Why Choose Us',
    'contact.trust.1': 'Trusted by 100+ Hong Kong agents',
    'contact.trust.2': 'No hidden fees or long-term contracts',
    'contact.trust.3': '24/7 dedicated support team',
    'contact.service.video': 'AI Video Property Content',
    'contact.service.video.desc': 'Transform property photos into cinematic videos',
    'contact.service.bot': 'Lead Capture Bot',
    'contact.service.bot.desc': '24/7 automated lead qualification',
    'contact.service.targeting': 'Predictive Targeting',
    'contact.service.targeting.desc': 'Find high-intent buyers automatically',
    'contact.service.consultation': 'Strategy Consultation',
    'contact.service.consultation.desc': 'Personalized marketing advice',
    'contact.form.back': 'Back',
    'contact.form.next': 'Continue',
    'contact.form.success': 'Sent Successfully',
    'contact.error.required': 'This field is required',
    'contact.error.email': 'Please enter a valid email address',
    
    // Thank You
    'thankyou.title': 'Thank You!',
    'thankyou.subtitle': 'Your message has been received.',
    'thankyou.desc': 'We have sent a confirmation email to your inbox. While you wait, why not schedule a free 15-minute strategy call with our team?',
    'thankyou.button': 'Book Consultation',
    'thankyou.back': 'Back to Home',
  },
  zh: {
    // Navigation
    'nav.home': '首頁',
    'nav.services': '服務',
    'nav.about': '關於我們',
    'nav.contact': '聯絡我們',
    'nav.getStarted': '立即開始',
    'nav.getAccess': '獲取權限',
    
    // Footer
    'footer.desc': "為香港地產專業人士建立更有意義的連結。真實策略，持續增長，以人為本的營銷。",
    'footer.explore': '探索',
    'footer.connect': '連結',
    'footer.rights': '版權所有。',
    
    // Home
    'home.badge': '新一代智能營銷基建',
    'home.hero.title': '自動化增長',
    'home.hero.subtitle': '專為精英地產代理而設',
    'home.hero.desc': '我們利用生成式影片、自動化代理和預測算法，助您在競爭對手之前鎖定優質買家。',
    'home.hero.cta.explore': '探索基建',
    'home.hero.cta.demo': '預約諮詢',
    'home.float.roi': '廣告回報率',
    'home.float.industry': '對比行業平均',
    'home.float.lead': '新合資格客源',
    'home.float.budget': '預算',
    'home.pillars.title': '智能優勢',
    'home.pillars.desc': '傳統營銷是被動且人手的。我們的基建是自動化、具預測性，並專為現代而設。',
    'home.pillars.video.title': '生成式影片',
    'home.pillars.video.desc': '我們自動將靜態照片轉化為電影級樓盤影片，提升 400% 互動率。',
    'home.pillars.video.detail': '我們的 AI 分析您的樓盤照片，製作出電影級的影片導覽，配備專業旁白、背景音樂和動態轉場。無需攝製隊。',
    'home.pillars.agents.title': '自動化代理',
    'home.pillars.agents.desc': '我們的自動化 CRM 系統全天候 24/7 即時回覆，在您醒來前已確認預算和意向。',
    'home.pillars.agents.detail': '不再錯失任何客源。我們的 AI 代理在 WhatsApp 和 Messenger 上即時回覆潛在買家，解答疑問並在您休息時預約睇樓。',
    'home.pillars.predictive.title': '預測性鎖定',
    'home.pillars.predictive.desc': '算法分析數千個數據點，識別準備交易的高資產淨值買家。',
    'home.pillars.predictive.detail': '停止在冷淡客源上浪費預算。我們分析數千個數據點，精準鎖定正在尋找您特定價格範圍和地區樓盤的買家。',

    'home.how.title': '運作流程',
    'home.how.desc': '簡單三步，徹底轉型您的客源生成模式。',
    'home.how.1.title': '連接',
    'home.how.1.desc': '將您的樓盤和社交帳戶整合到我們的安全平台。',
    'home.how.1.detail': '我們直接與您的 Facebook 和 Instagram 帳戶整合。只需將樓盤照片和主要賣點上載到我們的安全儀表板。',
    'home.how.2.title': '自動化',
    'home.how.2.desc': '我們的 AI 即時生成內容並啟動針對性廣告活動。',
    'home.how.2.detail': '我們的系統自動生成專業影片廣告，撰寫引人入勝的文案，並針對您的特定受眾設置目標廣告活動。',
    'home.how.3.title': '轉化',
    'home.how.3.desc': '直接在手機接收已預先篩選的合資格客源，隨時預約睇樓。',
    'home.how.3.detail': '坐享高質素客源湧入。您會收到已預約睇樓和準備入市的熱門客源的即時通知。',
    'home.pain.title': '停止依賴',
    'home.pain.subtitle': '過時的方法',
    'home.pain.1': '平台飽和意味著您的樓盤被淹沒。',
    'home.pain.2': '人手跟進對現代買家來說太慢。',
    'home.pain.3': '通用廣告將預算浪費在無效點擊上。',
    'home.solution.title': 'BasisHK 解決方案',
    'home.solution.1.title': '主導',
    'home.solution.1.desc': '以高頻影片內容主導動態消息。',
    'home.solution.2.title': '速度',
    'home.solution.2.desc': '利用自動化在秒速間回應，而非數小時。',
    'home.solution.3.title': '精準',
    'home.solution.3.desc': '只鎖定首 1% 的合資格買家。',
    'home.cta.title': '準備好',
    'home.cta.subtitle': '現代化？',
    'home.cta.desc': '加入首 1% 使用智能基建主導市場的代理行列。',
    'home.cta.button': '立即開始',
    'home.trusted.title': '深受頂尖發展商代理信賴',
    'home.gallery.title': '電影級製作',
    'home.gallery.subtitle': '看看我們的 AI 能為您的樓盤創造什麼。',
    'home.gallery.tag.luxury': '豪宅',
    'home.gallery.tag.tour': '虛擬導覽',
    'home.gallery.tag.promo': '社交推廣',
    'home.gallery.tag.drone': '航拍視角',

    // Case Studies
    'home.cases.title': '實證成效',
    'home.cases.subtitle': '香港代理的真實成功案例。',
    'home.cases.midlevels.title': '半山豪宅',
    'home.cases.midlevels.desc': '電影級影片導覽獲得超過 1.5 萬次自然觀看。',
    'home.cases.midlevels.stat1': '1.5 萬+',
    'home.cases.midlevels.label1': '影片觀看',
    'home.cases.midlevels.stat2': '14 天',
    'home.cases.midlevels.label2': '售出時間',
    'home.cases.kaitak.title': '啟德投資盤',
    'home.cases.kaitak.desc': '直度影片廣告在 48 小時內帶來 45 個客源。',
    'home.cases.kaitak.stat1': '45 個',
    'home.cases.kaitak.label1': '客源數量',
    'home.cases.kaitak.stat2': '$12',
    'home.cases.kaitak.label2': '客源成本',
    'home.cases.saikung.title': '西貢別墅',
    'home.cases.saikung.desc': '航拍展示吸引 12 位高資產淨值買家。',
    'home.cases.saikung.stat1': '12 位',
    'home.cases.saikung.label1': '合資格買家',
    'home.cases.saikung.stat2': '14.2%',
    'home.cases.saikung.label2': '互動率',

    // Services
    'services.title': '智能基建',
    'services.subtitle': '選擇適合您規模的增長引擎。',
    'services.monthly': '月費',
    'services.quarterly': '季費',
    'services.save': '節省 5%',
    'services.plan.starter': '入門版',
    'services.plan.growth': '增長版',
    'services.plan.agency': '機構版',
    'services.plan.starter.desc': '個人代理的必備自動化工具。',
    'services.plan.growth.desc': '高量產出者的進階工具。',
    'services.plan.agency.desc': '團隊的全方位基建。',
    'services.feature.video': 'AI 樓盤影片',
    'services.feature.bot': '客源捕捉機械人',
    'services.feature.content': '社交媒體內容',
    'services.feature.consultancy': '樓盤廣告諮詢服務',
    'services.feature.report': '表現報告',
    'services.feature.support': '電郵支援',
    'services.feature.manager': '專屬客戶經理',
    'services.feature.basic': '基本',
    'services.feature.advanced': '進階',
    'services.feature.posts': '則帖文',
    'services.feature.monthly': '每月',
    'services.feature.revisions': '無限次修改',
    'services.feature.weekly': '每週',
    'services.feature.aiOptimizer': 'AI 樓盤列表優化器',
    'services.feature.basicPortal': '基本品牌樓盤網站',
    'services.feature.limitedListings': '有限樓盤 + 自動同步',
    'services.feature.unlimitedListings': '無限樓盤 + 自動同步',
    'services.feature.adsBoosting2k': '廣告推廣服務（價值 $2,000）',
    'services.feature.adsBoosting4k': '廣告推廣服務（價值 $4,000）',
    'services.feature.videos': '條影片',
    'services.plan.videoOnly': '自訂 AI 樓盤影片',
    'services.plan.videoOnly.desc': '只需要影片？無需訂閱即可獲得高質素 AI 生成樓盤影片。',
    'services.videoSlider.label': '選擇影片數量',
    'services.videoSlider.perVideo': '每條影片',
    'services.videoOnly.feature1': '4K 電影級畫質',
    'services.videoOnly.feature2': '專業旁白',
    'services.videoOnly.feature3': '48 小時交付',
    'services.videoOnly.feature4': '無限次修改',
    'services.videoOnly.cta': '立即訂購影片',
    'services.select': '選擇計劃',
    'services.popular': '最受歡迎',
    'services.faq.title': '常見問題',
    'services.faq.subtitle': '關於我們服務和收費的詳細解答。',
    'services.faq.q1': '「無限次修改」是什麼意思？',
    'services.faq.a1': '我們希望您對內容百分百滿意。您可以對影片剪輯、字幕或廣告文案提出任意次數的修改要求，直到完全符合您的願景。',
    'services.faq.q2': '是否有最短合約期？',
    'services.faq.a2': '沒有，我們所有計劃都是按月收費。您可以隨時取消或升級。不過，選擇按季繳付可節省 5%。',
    'services.faq.q3': '多久可以收到第一條影片？',
    'services.faq.a3': '當您上載樓盤照片後，我們的 AI 會在幾分鐘內生成初稿。經您審閱後，最終潤飾版本通常在 48 小時內完成，並由我們的創意團隊進行修訂。',
    'services.faq.q4': '你們會處理廣告預算嗎？',
    'services.faq.a4': '廣告費用由您直接支付給平台（Facebook/Instagram）。我們的費用涵蓋管理、優化和創意製作。',
    'services.faq.q5': '什麼是高級潛在客戶捕獲機器人？',
    'services.faq.a5': '我們的高級潛在客戶捕獲機器人是一個全天候運作的 AI 助手。它通過詢問有關預算、偏好和時間表的關鍵問題來篩選潛在客戶，確保您只將時間花在購買意向高的潛在客戶身上。',
    'services.faq.q6': '預測性定位是如何運作的？',
    'services.faq.a6': '預測性定位利用機器學習分析市場趨勢和用戶行為。它能識別最有可能轉化的潛在買家，讓我們能在競爭對手之前將您的廣告投放給最相關的受眾。',
    'services.faq.q7': '專屬客戶經理負責什麼？',
    'services.faq.a7': '您的專屬客戶經理是您的戰略合作夥伴。他們負責監督您的營銷活動，提供月度績效報告，並提供個性化建議以優化您的營銷策略，確保達成您的目標。',

    // About
    'about.title': '由代理建立，為代理而設',
    'about.desc': '我們不只是技術開發者。我們是深明市場運作的地產老手。',
    'about.mission.1': 'BasisHK 源於挫折。作為曾在香港競爭激烈的市場打拼的前線代理，我們親眼目睹傳統營銷如何未能跟上數碼時代的步伐。',
    'about.mission.2': '我們花費多年時間建立了我們夢寐以求的工具：這些系統能自動化繁瑣工作，在我們睡覺時篩選客源，讓我們能專注於最重要的事情——促成交易。',
    'about.mission.3': '今天，我們以跨國企業級的技術賦能個人代理，為每位專業人士創造公平的競爭環境。',
    'about.stat.focus': '專注地產',
    'about.stat.uptime': '系統正常運行',
    'about.stat.growth': '致力於您的增長',
    'about.values.title': '核心價值',
    'about.values.integrity': '代理優先',
    'about.values.integrity.desc': '我們開發能解決實際問題的功能，而非花巧的玩具。',
    'about.values.innovation': '透明度',
    'about.values.innovation.desc': '絕無隱藏收費或虛榮指標。我們只追蹤能為您帶來收益的數據。',
    'about.values.results': '卓越',
    'about.values.results.desc': '我們相信每位代理都值得擁有世界級的基建。',
    'about.cta.title': '加入革命',
    'about.cta.button': '聯絡我們',

    // Contact
    'contact.title': '聯絡我們',
    'contact.desc': '對我們的服務感興趣？請填寫表格預約我們的營銷團隊諮詢。我們期待討論如何協助您發展地產業務。',
    'contact.hours.title': '辦公時間',
    'contact.hours.desc': '星期一至五：上午 9:00 - 下午 6:00',
    'contact.email.title': '電郵',
    'contact.form.firstName': '名字',
    'contact.form.lastName': '姓氏',
    'contact.form.agency': '地產代理公司',
    'contact.form.email': '電郵地址',
    'contact.form.phone': '電話號碼',
    'contact.form.budget': '營銷預算 (每月)',
    'contact.form.budget.placeholder': '選擇範圍',
    'contact.form.message': '訊息',
    'contact.form.message.placeholder': '請描述您目前的營銷挑戰...',
    'contact.form.submit': '提交查詢',
    'contact.form.submitting': '提交中...',
    'contact.toast.title': '已收到查詢',
    'contact.toast.desc': '感謝您聯絡 BasisHK。我們的代表將於 24 小時內回覆您的查詢。',
    
    // Contact Form - New Keys
    'contact.step1.title': '告訴我們關於您',
    'contact.step1.desc': '讓我們了解您，以便為您提供個性化體驗。',
    'contact.step2.title': '聯絡方式',
    'contact.step2.desc': '我們如何聯繫您討論您的需求？',
    'contact.step3.title': '您對什麼感興趣？',
    'contact.step3.desc': '選擇您感興趣的服務並告訴我們更多。',
    'contact.info.title': '聯繫我們',
    'contact.phone.title': '電話',
    'contact.response.time': '我們通常在工作日 24 小時內回覆。',
    'contact.trust.title': '為何選擇我們',
    'contact.trust.1': '超過 100 位香港代理信賴',
    'contact.trust.2': '無隱藏費用或長期合約',
    'contact.trust.3': '24/7 專屬支援團隊',
    'contact.service.video': 'AI 影片導覽',
    'contact.service.video.desc': '將樓盤照片轉化為電影級影片',
    'contact.service.bot': '潛在客戶捕獲機器人',
    'contact.service.bot.desc': '24/7 自動化客源篩選',
    'contact.service.targeting': '預測性鎖定',
    'contact.service.targeting.desc': '自動尋找高意向買家',
    'contact.service.consultation': '策略諮詢',
    'contact.service.consultation.desc': '個性化營銷建議',
    'contact.form.back': '返回',
    'contact.form.next': '繼續',
    'contact.form.success': '發送成功',
    'contact.error.required': '此欄位為必填',
    'contact.error.email': '請輸入有效的電郵地址',

    // Thank You
    'thankyou.title': '感謝您的查詢！',
    'thankyou.subtitle': '我們已收到您的訊息。',
    'thankyou.desc': '確認郵件已發送至您的郵箱。在等待期間，不妨直接預約 15 分鐘免費策略諮詢？',
    'thankyou.button': '預約諮詢',
    'thankyou.back': '返回首頁',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
